name: Vwap CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    types:
      - opened
  pull_request_target:  # Handles merge events safely
    types:
      - closed

jobs:
  build:
    # Skip if PR is closed without merge
    if: github.event_name != 'pull_request_target' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Compile only - no tests
      - name: Build
        run: mvn clean compile

      # Run unit tests
      - name: Run Unit Tests
        run: mvn test

      # Package without running tests again
      - name: Package
        run: mvn package -DskipTests

      #      - name: Run Integration Tests
      #        run: mvn verify -P integration-test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar